image: ghcr.io/szab100/gitpod-k3s-qemu
checkoutLocation: gitpod-k3s
tasks:
  - name: K3S (QEMU)
    command: |
      /opt/qemu-k3s/qemu.sh
  - name: Main
    command: |
      /opt/qemu-k3s/prepare-k3s.sh