image:
  file: .gitpod.Dockerfile
checkoutLocation: gitpod-k3s
tasks:
  - before: /opt/qemu-k3s/qemu.sh
  - init: |
      /opt/qemu-k3s/ws-init.sh
  - command: |
      source /opt/qemu-k3s/ws-start.sh
